language: python
python:
  - 3.5
  - 3.6

os:
    - linux

compiler:
    - gcc

services: docker
sudo: required

env:
    global:
        - UNICODE_WIDTH=32
        - PLAT=x86_64
        - MB_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
        - VERSION=$(echo $TRAVIS_TAG | sed s/v//)

addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3
        packages:
            - cmake
            - cmake-data

matrix:
    fast_finish: true
    include:
        - python: 3.7
          dist: xenial
          sudo: true
        - python: 3.8
          dist: xenial
          sudo: true
        - os: linux
          compiler: clang
          env:
              - MATRIX_EVAL="CC=clang && CXX=clang++"
              - SCAN="scan-build --status-bugs"
              - SOURCEDEPLOY=1
              - WERROR="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-Werror"
              - MKDOC="-DBUILD_DOC=ON -DSPHINX_ARGS=-WT"
        - os: osx
          python: 3.5
          language: generic
          env:
            - MB_PYTHON_VERSION=3.5
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          language: generic
          python: 3.6
          env:
            - MB_PYTHON_VERSION=3.6
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          language: generic
          python: 3.7
          env:
            - MB_PYTHON_VERSION=3.7
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: osx
          language: generic
          python: 3.8
          env:
            - MB_PYTHON_VERSION=3.8
            - MACOSX_DEPLOYMENT_TARGET=10.9
        - os: linux
          arch: s390x
          name: bigendian
          language: generic
          before_install: skip
          install: skip
          before_script: skip
          deploy:
          script:
            - docker build -t dlisio -f .travis/bigendian/Dockerfile .

before_install:
    - eval "${MATRIX_EVAL}"
    - unset -f pushd
    - unset -f popd
    - git clone https://github.com/fmtlib/fmt.git
    - mkdir fmt/build
    - pushd fmt/build
    - cmake -DFMT_TEST=OFF -DFMT_DOC=OFF ..
    - make
    - sudo make install
    - popd
    - git clone https://github.com/equinor/layered-file-protocols.git
    - mkdir layered-file-protocols/build
    - pushd layered-file-protocols/build
    - cmake -DBUILD_SHARED_LIBS=ON
            -DLFP_FMT_HEADER_ONLY=ON
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib
            -DBUILD_TESTING=OFF ..
    - make
    - sudo make install
    - popd
    - git clone https://github.com/matthew-brett/multibuild
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - pip install --upgrade -r python/requirements-dev.txt
    - bandit -c bandit.yml -r python/

before_script:
    - mkdir build
    - pushd build
    - $SCAN cmake -DCMAKE_BUILD_TYPE=Release
                  -DBUILD_SHARED_LIBS=ON
                  -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib
                  $MKDOC
                  ${WERROR}
                  ..
    - popd

script:
    - pushd build
    - make
    - ctest --output-on-failure
    - sudo make install
    - popd
    # install works, so remove the _skbuild because it having root permissions
    # from make install breaks build_wheel
    - sudo rm -rf python/_skbuild
    - build_wheel python $PLAT
    - install_run $PLAT
    - mv wheelhouse python/dist

before_deploy:
    - pushd python

after_deploy:
    - popd

deploy:
    - provider: pypi
      skip_cleanup: true
      skip_upload_docs: true
      user: statoil-travis
      distributions: --skip-cmake build
      password:
        secure: NKjQaDPPCDE8C7f1c3rNdVInJUBkp1DegubXyzbNwLz0k/JiQv5IoTKh7ehJnZoOaHaFa8zTMSZYT9VypgvRp2sziCdI/piEASCTbv5lJAZ1ELE2aSiVeSCuBbq/3BFp5YqfuqPjrIy32xvlbCU2rwhRNo4eVrfop8pYdMZeWSAvn+FDSNaVPhUs0E4HKI57ROkjDJvnMmRQpcOYQslxUgGth7F7F2kGxP0Z+L0DmsAnxPYjLzjNe3DzD9EMfegPG5il+J7GmKJrLNNhGyIET+cxKKaODgjVSqaiZ5tgiNjAALxZMiZz0KyYclo/TOiKvuimWjSruDAiSY2NsacF6SW83qkfGZHCURL/nrHnyTEhzY3/qRN2HuSeE51BTFTrw306HzdCHDp8E7nlLz44/F3X+UaL8OinuZvj5IaaJSX9Q0eU10dxvH5ezgZa0CgAIK3N/bvjSMEFJhkG5/MlRk4pmo4HsjX8EduskJQMV+qc0pE4JHMZkRqlFY+LjkyEgw73iIqrpXBkSnkSM8Q4t7sECyTup7nhMbbkl1MehT+uKC+9dy1cZw2AMsRcs+WLzSOV8jU6IY1Iwh/q+N8q6Y08ek6lmGXGMKPzPQCsNQ6B2NpJ0zb6PRqMa4d5HS+b+ar/B4nMrltzRzP8bRJYrmx1cQXnJ1gLwgpsBhfEnf0=
      on:
        tags: true
        condition: -z $SOURCEDEPLOY
